### ISSUE TITLE
Will you release the caffe or pytorch code?

### ISSUE THREAD

**Issue by soeaver** [ZhouYanzhao/ORN#5]
Thanks!

**Comment by ZhouYanzhao** [comment]
Sure. I have already implemented a simplified version of ORN on Caffe/pyTorch (supports 1x1 or 3x3 ARFs only). If you need it, I will find some time next week to clean it up and release. Thanks for your interest!

**Comment by soeaver** [comment]
@ZhouYanzhao 
That' s very awesome! Looking forward your future work.

**Comment by samson-wang** [comment]
Waiting for the release for months!
I've tried the torch version. It's much better than my caffe implementation. There must be something I misunderstood. Hope the official release will come out soon.

**Comment by ZhouYanzhao** [comment]
@samson-wang Thank you for your patience! The alpha version of Caffe/PyTorch implementation (PR #6) is released for your reference.

**Comment by samson-wang** [comment]
@ZhouYanzhao  I've tried it. Thank you!
In my test case, ORAlign is much better than the ORPooling. However, there is no ORAlign in the caffe implementation.
An interesting observation. I tried to use `pad:2` in `conv1` instead of resizing image to `32x32`. The test accuracy drops a lot. `pad:1` is OK.

**Comment by ZhouYanzhao** [comment]
@samson-wang ORAlign is not supported in the alpha version of caffe implementation, but it should be easy for you to port it from the torch/pytorch implementation :) As for your observation, my little guess is that inappropriate padding could cause misalignment of hierarchical receptive fields.

I'll close this issue since the implementations are released. If you have more questions, feel free to:
* reopen it
* open new issues
* contact me directly  [yzhou.work@outlook.com](mailto:yzhou.work@outlook.com)
